export {default as Dashboard} from './Dashboard'
export {default as Sidebar} from './Sidebar'
export {default as Topbar} from './Topbar'
export {default as Payments} from './Payment'
export {default as Contact} from './Contact'
export { default as Invoice} from './Invoice'
export { default as Calander} from './Calander'
export { default as Faq } from './Faq'
export { default as Bar } from './Bar'
export { default as Line } from './Lineindex'
export {default as OTPbox} from './OTPbox'