export {default as Navbar} from './Navbar'
export {default as Feed} from './Feed'
export {default as Infobar} from './Infobar'
export {default as Top} from './Top'
export {default as SomeInfo} from './SomeInfo'
export {default as Products} from './Products'
export {default as Why} from './Why'
export {default as Footer} from './Footer'
export {default as Register} from './Register'
export {default as Login} from './Login'
export {default as Common} from './Common'
export {default as Dropdown} from './Dropdown'

export {default as OTPBox} from './OTPBox'